spring:
  profiles:
    active: dev


flyway:
  enabled: true
  locations: classpath:migration
  fail-on-missing-locations: true
  baseline-on-migrate: true

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml